# Generated by Django 2.2.3 on 2019-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weightapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_data', models.DateTimeField(verbose_name='Date & Time')),
                ('weight', models.IntegerField(default=0)),
                ('bodyfat', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
