# Generated by Django 2.2.3 on 2019-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0002_auto_20190717_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightapp',
            name='category',
            field=models.CharField(default='Leg', max_length=10),
            preserve_default=False,
        ),
    ]
