# Generated by Django 2.2.3 on 2019-07-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0003_weightapp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightapp',
            name='Myweight',
            field=models.IntegerField(default=0),
        ),
    ]
