# Generated by Django 2.2.3 on 2019-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightapp', '0005_remove_weightapp_myweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightapp',
            name='use_date',
            field=models.DateTimeField(verbose_name='Date & Date'),
        ),
    ]
